###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: payment-mysql
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=test_user_name
      - MYSQL_PASSWORD=test_password
    ports:
      - "8085:3306"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: payment-php-fpm
    working_dir: /application
    environment:
      PHP_IDE_CONFIG: "serverName=payment-reg"
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

  webserver:
    image: nginx:alpine
    container_name: payment-webserver
    working_dir: /application
    volumes:
        - .:/application
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8084:80"
    depends_on:
     - php-fpm

#  memcached:
#   image: memcached:alpine
#   container_name: payment-memcached