version: "3.7"
services:
  reg-mariadb:
    image: mariadb:10.4
    container_name: payment-mariadb
    working_dir: /app
    volumes:
      - ./../:/app
    environment:
      - MYSQL_ROOT_PASSWORD=db_docker_123
      - MYSQL_DATABASE=db_reg
      - MYSQL_USER=db_reg_username
      - MYSQL_PASSWORD=db_reg_password
    ports:
      - "127.0.0.1:8085:3306"

  reg-php-fpm:
    build: ./php-fpm
    container_name: payment-php-fpm
    working_dir: /app
    environment:
      PHP_IDE_CONFIG: "serverName=reg-payment"
    volumes:
      - ./../:/app
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

  reg-webserver:
    image: nginx:alpine
    container_name: payment-webserver
    working_dir: /app
    volumes:
        - ./../:/app
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "127.0.0.1:8084:80"
    links:
     - reg-php-fpm
