parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Twig\:
        resource: '../src/Twig'
        tags: ['twig.extension']

    App\Service\LoginGate\LoginGate:
        arguments:
            $maxAttempts: '%env(int:LOGIN_GATE_MAX_ATTEMPTS)%'
